// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class SlimeAscentResources
{
        public const string achievement_sapphire_cave_complete = "CgkIoZyF-coJEAIQAw"; // <GPGSID>
        public const string achievement_emerald_cave_complete = "CgkIoZyF-coJEAIQBA"; // <GPGSID>
        public const string leaderboard_sapphire_cave_top_height = "CgkIoZyF-coJEAIQBw"; // <GPGSID>
        public const string achievement_amethyst_caves_complete = "CgkIoZyF-coJEAIQAg"; // <GPGSID>
        public const string leaderboard_emerald_cave_top_height = "CgkIoZyF-coJEAIQCA"; // <GPGSID>
        public const string achievement_in_one_go = "CgkIoZyF-coJEAIQBQ"; // <GPGSID>
        public const string leaderboard_amethyst_cave_top_height = "CgkIoZyF-coJEAIQBg"; // <GPGSID>
        public const string achievement_game_complete = "CgkIoZyF-coJEAIQAQ"; // <GPGSID>

}

